[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-ledger-tool"
description = "Blockchain, Rebuilt for Scale"
version = "1.0.25"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
bs58 = "0.3.1"
bytecount = "0.6.0"
clap = "2.33.1"
csv = "1.1.3"
histogram = "*"
serde_json = "1.0.46"
serde_yaml = "0.8.11"
solana-clap-utils = { path = "../clap-utils", version = "1.0.25" }
solana-cli = { path = "../cli", version = "1.0.25" }
solana-ledger = { path = "../ledger", version = "1.0.25" }
solana-logger = { path = "../logger", version = "1.0.25" }
solana-runtime = { path = "../runtime", version = "1.0.25" }
solana-sdk = { path = "../sdk", version = "1.0.25" }
solana-vote-program = { path = "../programs/vote", version = "1.0.25" }
solana-stake-program = { path = "../programs/stake", version = "1.0.25" }
solana-transaction-status = { path = "../transaction-status", version = "1.0.25" }
tempfile = "3.1.0"

[dev-dependencies]
assert_cmd = "0.12"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
